spring:
  application:
    name: springboot-k8s-jenkins-poc

server:
  port: 3030

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health
#  endpoint:
#    health:
#      probes:
#        enabled: true   # adds /actuator/health/liveness and /actuator/health/readiness
#      show-details: never